apiVersion: v1
kind: ConfigMap
metadata:
  name: ratings-service
  namespace: northgate
data:
  JAVA_OPTS: "-Xms256m -Xmx1024m"
  NORTHGATE_EXPORT_DIR: "/var/northgate/exports"
  SPRING_PROFILES_ACTIVE: "staging"
